### ISSUE TITLE
SFTP and tool instructions

### ISSUE THREAD

**Issue by kirenotneb** [AI-READI/fairhub-portal#115]
Add documentation to the download page providing instructions as to how to use various tools to download the data. @ejdysinger has provided the attached write up for using a number of the tools and techniques.

[download_instructions.md](https://github.com/AI-READI/fairhub-portal/files/15491711/download_instructions.md)

**Comment by heathharrelson** [comment]
@kirenotneb, @ejdysinger — looking at the Markdown file, it's not clear to me where to get the SAS URL used by AzCopy and Rclone. Do we already store this somewhere or have API to retrieve it?

**Comment by kirenotneb** [comment]
Oh shoot, I forgot the instructions for AzCopy and Rclone were in there. That's issue #118 which is a bit further down the list. I'd suggest just sticking with the FileZilla ones for the moment.

**Comment by heathharrelson** [comment]
@kirenotneb, not a problem. It's easy enough to just include the FileZilla instructions.

**Comment by heathharrelson** [comment]
Replaced command line SSH instructions with FileZilla instructions from the Markdown file in #127.
