### ISSUE TITLE
Download SSH key instead of copying to clipboard

### ISSUE THREAD

**Issue by kirenotneb** [AI-READI/fairhub-portal#119]
Currently users are presented with a button to copy the SSH key to their clipboard which they must then paste in a file along with the key in a code block they can look at and copy manually. The original design was that they would be provided with the button to download the SSH key file, but we encounted issues when this was deployed to other evnironments. Ideally we will review why this wasn't working and provide users the option to download the key instead of having to copy it.

**Comment by heathharrelson** [comment]
Fixed a bug in the API endpoint that serves the key download, allowing the key to be downloaded from the Azure environment. Fixed in #127.
