### ISSUE TITLE
Filter "Dataset Uses" records

### ISSUE THREAD

**Issue by kirenotneb** [AI-READI/fairhub-portal#120]
The Dataset Uses report in the fairhub.io portal will only display "approved" datasets. This will be governed by the Approved property of the the request record as described in the [pipeline status issue](https://github.com/AI-READI/watermark-pipeline/issues/13).

**Comment by heathharrelson** [comment]
This has been implemented and has been deployed to the staging environment. See the "Dataset Uses" tab here:

https://staging.fairhub.io/datasets/1
